source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserListView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('list/', UserListView.as_view(), name='list'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from webapp.views import IndexView, TaskCreateView, TaskDeleteView, TaskView, TaskUpdateView, \
    ProjectView, ProjectCreateView, TaskListView, ProjectUpdateView, ProjectDeleteView, ProjectPermissonUpdateView
from django.contrib.auth.views import LoginView, LogoutView
# from accounts.views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexView.as_view(), name='index'),
    path('project/', include([
        path('<int:pk>/', ProjectView.as_view(), name='project_view'),
        path('add/', ProjectCreateView.as_view(), name='project_create'),
        path('<int:pk>/update', ProjectUpdateView.as_view(), name='project_update'),
        path('<int:pk>/delete', ProjectDeleteView.as_view(), name='project_delete'),
        path('<int:pk>/tasks/add/', TaskCreateView.as_view(), name='task_create'),
        path('<int:pk>/edit_user', ProjectPermissonUpdateView.as_view(), name='project_user_edit')
    ])),

    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),

    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from datetime import date


class Tasks(models.Model):
    project = models.ForeignKey('webapp.Project', related_name='tasks', on_delete=models.CASCADE, verbose_name='проект')
    summary = models.CharField(default='My title', max_length=200, null=False, blank=False, verbose_name='Название',
                               validators=[MinLengthValidator(10)])
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    status = models.ForeignKey('webapp.Status', related_name='status', on_delete=models.PROTECT, verbose_name='Статус')
    types = models.ManyToManyField('webapp.Type', related_name='tasks', blank=True, verbose_name='Тип')
    task_create = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    task_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return "{}. {}".format(self.pk, self.summary)

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"


class Status(models.Model):
    name = models.CharField(default='Task', max_length=20, null=False, blank=False, verbose_name='Название статуса')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Статус'
        verbose_name_plural='Статусы'


class Type(models.Model):
    name = models.CharField(default='New', max_length=20, null=False, blank=False, verbose_name='Название типа')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class Project(models.Model):
    date_start = models.DateField(verbose_name='Дата начала', default=date.today)
    date_end = models.DateField(verbose_name='Дата окончания', blank=True, null=True)
    name = models.CharField(default='HELLO WORLD!', max_length=300, verbose_name='Название проекта')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    author = models.ManyToManyField(get_user_model(), related_name='projects', blank=True, verbose_name='Пользователь', default=1)

    def __str__(self):
        return "{}. {}".format(self.pk, self.name)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

source/webapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from webapp.models import Tasks, Project
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, CreateView

from django.http import HttpResponseNotAllowed
from .forms import TaskForm, SearchForm, ProjectForm
from django.db.models import Q, F


class IndexView(ListView):
    template_name = 'project/index.html'
    context_object_name = 'projects'
    paginate_by = 5
    paginate_orphans = 0

    def get_context_data(self, *, object_list=None, **kwargs):
        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            kwargs['search'] = search
        kwargs['form'] = form
        return super().get_context_data(object_list=object_list, **kwargs)

    def get_queryset(self):
        data = Project.objects.all()

        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search:
                data = data.filter(Q(name__icontains=search) | Q(description__icontains=search))

        return data.order_by('-date_start')


class ProjectView(DetailView):
    template_name = 'project/project_view.html'
    model = Project
    paginate_tasks_by = 5
    paginate_tasks_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        tasks, page, is_paginated = self.paginate_tasks(self.object)
        context['tasks'] = tasks
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_tasks(self, project):
        tasks = project.tasks.all().order_by('-task_create')
        if tasks.count() > 0:
            paginator = Paginator(tasks, self.paginate_tasks_by, orphans=self.paginate_tasks_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return tasks, None, False


class ProjectCreateView(CreateView):
    template_name = 'project/project_create.html'
    form_class = ProjectForm
    model = Project

    def get_success_url(self):
        return reverse('project_view', kwargs={'pk': self.object.pk})

class TaskListView(ListView):
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'
    paginate_by = 10
    paginate_orphans = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            kwargs['search'] = search
        kwargs['form'] = form
        return super().get_context_data(object_list=object_list, **kwargs)

    def get_queryset(self):
        data = Tasks.objects.all()

        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search:
                data = data.filter(Q(summary__icontains=search) | Q(description__icontains=search))

        return data.order_by('-task_create')

class TaskView(TemplateView):
    template_name = 'task/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pk = self.kwargs.get('pk')
        task = get_object_or_404(Tasks, pk=pk)

        context['task'] = task
        return context


class TaskCreateView(FormView):
    template_name = 'task/task_create.html'
    form_class = TaskForm

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task_view', kwargs={'pk': self.task.pk})


class UpdateView(FormView):
    template_name = 'task/task_update.html'
    form_class = TaskForm

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Tasks, pk=pk)

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.task
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task_view', kwargs={'pk': self.task.pk})


class DeleteView(View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        task = get_object_or_404(Tasks, pk=pk)
        return render(request, 'task/task_delete.html', context={'task': task})

    def post(self, request, pk):
        task = get_object_or_404(Tasks, pk=pk)
        task.delete()
        return redirect('index')

source/webapp/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy

from webapp.models import Project
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from webapp.forms import SearchForm, ProjectForm, ProjectUpdateForm
from django.db.models import Q


class IndexView(ListView):
    template_name = 'project/index.html'
    context_object_name = 'projects'
    paginate_by = 5
    paginate_orphans = 0

    def get_context_data(self, *, object_list=None, **kwargs):
        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            kwargs['search'] = search
        kwargs['form'] = form
        return super().get_context_data(object_list=object_list, **kwargs)

    def get_queryset(self):
        data = Project.objects.all()

        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search:
                data = data.filter(Q(name__icontains=search) | Q(description__icontains=search))

        return data.order_by('-date_start')


class ProjectView(DetailView):
    template_name = 'project/project_view.html'
    model = Project
    paginate_tasks_by = 5
    paginate_tasks_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        tasks, page, is_paginated = self.paginate_tasks(self.object)
        context['tasks'] = tasks
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_tasks(self, project):
        tasks = project.tasks.all().order_by('-task_create')
        if tasks.count() > 0:
            paginator = Paginator(tasks, self.paginate_tasks_by, orphans=self.paginate_tasks_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return tasks, None, False


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    form_class = ProjectForm
    model = Project
    permission_required = 'webapp.add_project'

    def form_valid(self, form):
        form.save()
        form.instance.author.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('project_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user.groups.filter(pk=2) or self.request.user.pk == 1


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/project_update.html'
    form_class = ProjectForm
    model = Project
    context_object_name = 'project'
    permission_required = 'webapp.change_project'

    def get_success_url(self):
        return reverse('project_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user.groups.filter(pk=2) or self.request.user.pk == 1


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    success_url = reverse_lazy('index')
    permission_required = 'webapp.delete_project'

    def has_permission(self):
        return super().has_permission() and self.request.user.groups.filter(pk=2) or self.request.user.pk == 1


class ProjectPermissonUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'project/user_edit.html'
    form_class = ProjectUpdateForm
    model = Project
    context_object_name = 'project'
    permission_required = 'webapp.change_project'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().author.all()

    def get_success_url(self):
        return reverse('project_view', kwargs={'pk': self.object.pk})

source/webapp/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from webapp.models import Tasks, Project
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

from webapp.forms import TaskForm, SearchForm
from django.db.models import Q


class TaskListView(ListView):
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'
    paginate_by = 10
    paginate_orphans = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            kwargs['search'] = search
        kwargs['form'] = form
        return super().get_context_data(object_list=object_list, **kwargs)

    def get_queryset(self):
        data = Tasks.objects.all()

        form = SearchForm(data=self.request.GET)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search:
                data = data.filter(Q(summary__icontains=search) | Q(description__icontains=search))

        return data.order_by('-task_create')


class TaskView(TemplateView):
    template_name = 'task/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pk = self.kwargs.get('pk')
        task = get_object_or_404(Tasks, pk=pk)

        context['task'] = task
        return context


class TaskCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'task/task_create.html'
    form_class = TaskForm
    model = Tasks
    permission_required = 'webapp.add_tasks'

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        form.save_m2m()
        return redirect('project_view', pk=project.pk)

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.author.all()


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'task/task_update.html'
    form_class = TaskForm
    model = Tasks
    context_object_name = 'task'
    permission_required = 'webapp.change_tasks'

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.author.all()

    def get_success_url(self):
        return reverse('task_view', kwargs={'pk': self.object.pk})


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'task/task_delete.html'
    permission_required = 'webapp.delete_tasks'
    model = Tasks
    success_url = reverse_lazy('index')

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.author.all()

source/webapp/templates/project/index.html
{% extends 'base.html' %}
{% block title %}Projects{% endblock %}
{% block styles %}<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">{% endblock %}

{% block search %}
    <div class="search-form">
            <form action="{% url 'index' %}" method="GET">
                <input type="text" name="search">
                <input type="submit" value="Найти">
            </form>
        </div>
{% endblock %}
{% block content %}
<h1>Проекты:</h1>
    {% include 'partial/project_list.html' %}
{% endblock %}

source/webapp/templates/project/project_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
    <h1>Create Project</h1>

    {% url 'project_create' as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' %}
{% endblock %}

source/webapp/templates/project/project_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li><a href="{% url 'project_view' project.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Вы уверены, что хотите удалить проект "{{ project.name }}"?</h1>
    <p>Date create: {{ project.date_start }}</p>
    <p>Date end: {{ project.date_end }}</p>
    <form action="{% url "project_delete" project.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" value="Да" class="button accept">Подтвердить</button>
        <a href="{% url 'project_view' project.pk %}" class="button cancel">Отмена</a>
    </form>
    <h3>Содержимое статьи: </h3>
    <p>{{ project.description }}</p>
{% endblock %}

source/webapp/templates/project/project_update.html
{% extends "base.html" %}

{% block title %}Update{% endblock %}

{% block menu %}
    <li><a href="{% url 'project_view' project.pk %}">Cancel</a></li>
{% endblock %}

{% block content %}
    <h1>Update Project</h1>
        {% url 'project_update' pk=project.pk as action_url %}
        {% include 'partial/form.html' with form_method='post' action_url=action_urls %}
{% endblock %}

source/webapp/templates/project/project_view.html
{% extends 'base.html' %}

{% block title %}View{% endblock %}

{% block menu %}
    {% if perms.webapp.change_project or request.user.pk == 1 %}
        <li><a href="{% url 'project_update' project.pk %}">Update Project</a></li>
    {% endif %}
    {% if perms.webapp.change_project or request.user.pk == 1 %}
        <li><a href="{% url 'project_delete' project.pk %}">Delete Project</a></li>
    {% endif %}
    {% if perms.webapp.change_project and request.user in project.author.all %}
        <li><a href="{% url 'project_user_edit' project.pk %}">Edit User</a></li>
    {% endif %}
    {% if perms.webapp.add_tasks and request.user in project.author.all %}
        <li><a href="{% url 'task_create' project.pk %}">Add Task</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="box">
        <h1>{{ project.name }}</h1>
        <p class="pre">{{ project.description }}</p>
        <p>Пользователи:</p>
        {% for author in project.author.all %}
            <a href="{% url 'accounts:detail' author.pk %}">{{ author }}</a><br/>
        {% endfor %}
        <p>Date start: {{ project.date_start }}</p>
        <p>Date end:
        {% if project.date_end %}
            {{ project.date_end}}
        {% else %}
            No end date
        {% endif %}</p>
        <hr>
        <h3>Tasks:</h3>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% for task in tasks %}
            <div class="box">
                <a href="{% url 'task_delete' task.pk %}" ><i class="far fa-trash-alt"></i></a>
                <a href="{% url 'task_update' task.pk %}" ><i class="far fa-edit"></i></a><br/>
                <h3><a href="/tasks/{{ task.pk }}" class="card-button">{{ task.summary }}</a></h3>
                <p>Статус: {{ task.status }}</p>
                <p>Дата выполнения: {{ task.task_create }}</p>
            </div>
        {% empty %}
            <p>Нет задач</p>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/project/user_edit.html
{% extends "base.html" %}

{% block title %}Permission Edit{% endblock %}

{% block menu %}
    <li><a href="{% url 'project_view' project.pk %}">Cancel</a></li>
{% endblock %}

{% block content %}
    <h1>Update Project</h1>
        {% url 'project_update' pk=project.pk as action_url %}
        {% include 'partial/form.html' with form_method='post' action_url=action_urls %}
{% endblock %}